set_tag(c("ambientnoise", "asciify", "attituderisk", "brownianbridge",
  "ccsclass", "chdss", "chdss2018", "cogsciclass", "compcogscisydney",
  "conjunction", "contextbandit", "curiousbandit", "deception",
  "djnavarroblog", "echochambers", "evidence-selection", "expex",
  "ggplot", "githubpages", "hugoslum", "itsraining", "kidbandit",
  "lsrbook", "mindsmachines", "mipsmops", "multimodal", "mymemes",
  "oddsandends", "ozunconf", "projects", "psyc2071", "psyr", "rainbowr",
  "rladiessydneyblog", "satrdayjoburg", "skilledbandits", "skyliner",
  "slumdown", "sydneyopenresearch", "thegitplace", "tidylsr", "tidylsrbook",
  "typestokens", "uncertprot", "unswpsychwomen", "whalen", "workbch",
  "xprmntr"), )
